version: '3.4'
services:

  uwsgi:
    build:
      context: .
      target: uwsgi
    volumes:
      - ../db:/db
    networks:
      libcsearch:
        ipv4_address: 10.0.200.10
    restart: always
    logging:
      driver: syslog
      options:
        tag: uwsgi

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      libcsearch:
        ipv4_address: 10.0.200.11
    restart: always
    logging:
      driver: syslog
      options:
        tag: elasticsearch

volumes:
  data01:
    driver: local

networks:
  libcsearch:
    ipam:
      config:
        - subnet: 10.0.200.0/24
